name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # This allows manual trigger of the workflow

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Install Allure Commandline
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk  # Install Java (Allure requires Java)
        curl -o allure-commandline.zip -L "https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.zip"  # Download Allure CLI
        unzip allure-commandline.zip -d allure  # Unzip Allure
        sudo ln -s $PWD/allure/bin/allure /usr/local/bin/allure  # Create symbolic link to the allure command
        allure --version  # Ensure allure is available in the system PATH

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: allure-report/
        retention-days: 30

    - name: Send email notification
      if: ${{ always() }}  # This ensures the step is always run, whether the tests pass or fail
      run: |
        sudo apt-get update
        sudo apt-get install -y msmtp  # Installing msmtp for sending email via SMTP

        echo "from=${{ secrets.EMAIL_USER }}" > ~/.msmtprc
        echo "auth=login" >> ~/.msmtprc
        echo "user=${{ secrets.EMAIL_USER }}" >> ~/.msmtprc
        echo "password=${{ secrets.EMAIL_PASSWORD }}" >> ~/.msmtprc
        echo "host=smtp.gmail.com" >> ~/.msmtprc
        echo "port=587" >> ~/.msmtprc
        echo "tls=on" >> ~/.msmtprc
        echo "logfile=/tmp/msmtp.log" >> ~/.msmtprc

        # Send email on job completion (success or failure)
        echo -e "Subject: GitHub Actions Test Completion Report\n\nYour Playwright tests have completed successfully.\n\nVisit the report: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | msmtp ${{ secrets.NOTIFY_EMAIL }}
