name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Install msmtp and send email notification
      if: ${{ always() }}
      run: |
        sudo apt-get update
        sudo apt-get install -y msmtp

        # Create .msmtprc file
        echo "from=${{ secrets.EMAIL_USER }}" > ~/.msmtprc
        echo "auth=login" >> ~/.msmtprc
        echo "user=${{ secrets.EMAIL_USER }}" >> ~/.msmtprc
        echo "password=${{ secrets.EMAIL_PASSWORD }}" >> ~/.msmtprc
        echo "host=smtp.gmail.com" >> ~/.msmtprc
        echo "port=587" >> ~/.msmtprc
        echo "tls=on" >> ~/.msmtprc
        echo "logfile=/tmp/msmtp.log" >> ~/.msmtprc

        # Debug: Output the contents of .msmtprc
        cat ~/.msmtprc

        # Send email notification
        echo -e "Subject: GitHub Actions Test Completion Report\n\nYour Playwright tests have completed successfully.\n\nVisit the report: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | msmtp ${{ secrets.NOTIFY_EMAIL }}
