name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # This allows manual trigger of the workflow

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Install Allure Commandline (via npm)
      run: |
        npm install -g allure-commandline --save-dev

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: allure-report/
        retention-days: 30

    - name: Install msmtp and send email notification
      if: ${{ always() }}
      run: |
        # Install msmtp
        sudo apt-get update
        sudo apt-get install -y msmtp

        # Create or overwrite .msmtprc with the correct syntax
        echo "from=\"${{ secrets.EMAIL_USER }}\"" > ~/.msmtprc
        echo "auth=login" >> ~/.msmtprc
        echo "user=\"${{ secrets.EMAIL_USER }}\"" >> ~/.msmtprc
        echo "password=\"${{ secrets.EMAIL_PASSWORD }}\"" >> ~/.msmtprc
        echo "host=smtp.gmail.com" >> ~/.msmtprc
        echo "port=587" >> ~/.msmtprc
        echo "tls=on" >> ~/.msmtprc
        echo "logfile=/tmp/msmtp.log" >> ~/.msmtprc

        # Debug: Output the contents of .msmtprc to check formatting
        echo "Checking contents of .msmtprc:"
        cat ~/.msmtprc

        # Check for hidden characters or formatting issues
        echo "Checking for hidden characters in .msmtprc:"
        cat -v ~/.msmtprc

        # Verify file permissions for .msmtprc (to ensure msmtp can access it)
        ls -l ~/.msmtprc

        # Send email notification (single email address for now)
        echo -e "Subject: GitHub Actions Test Completion Report\n\nYour Playwright tests have completed successfully.\n\nVisit the report: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | msmtp "${{ secrets.NOTIFY_EMAIL }}"
