name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Install Allure Commandline
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        npm install -g allure-commandline
        allure --version

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: allure-report/
        retention-days: 30

    - name: Debug GitHub Secrets Access
      run: |
        echo "Resolved EMAIL_USER: '${{ secrets.EMAIL_USER }}'"
        echo "Resolved EMAIL_PASSWORD: '${{ secrets.EMAIL_PASSWORD }}'"
        echo "Resolved NOTIFY_EMAIL: '${{ secrets.NOTIFY_EMAIL }}'"

    - name: Send email notification
      if: ${{ always() }}
      run: |
        sudo apt-get update
        sudo apt-get install -y msmtp

        # Write the .msmtprc file
        echo "from=${{ secrets.EMAIL_USER }}" > ~/.msmtprc
        echo "auth=login" >> ~/.msmtprc
        echo "user=${{ secrets.EMAIL_USER }}" >> ~/.msmtprc
        echo "password=${{ secrets.EMAIL_PASSWORD }}" >> ~/.msmtprc
        echo "host=smtp.gmail.com" >> ~/.msmtprc
        echo "port=587" >> ~/.msmtprc
        echo "tls=on" >> ~/.msmtprc
        echo "logfile=/tmp/msmtp.log" >> ~/.msmtprc

        # Debug the contents of the .msmtprc file
        cat ~/.msmtprc

        # Send the email
        echo -e "Subject: GitHub Actions Test Completion Report\n\nYour Playwright tests have completed successfully.\n\nVisit the report: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | msmtp ${{ secrets.NOTIFY_EMAIL }}
