- name: Deploy Allure report to GitHub Pages
if: ${{ always() }}  # Ensure this step runs even if previous steps fail
run: |
  # Deploy Allure report to GitHub Pages
  git config --global user.name "GitHub Actions"
  git config --global user.email "actions@github.com"
  
  # Clone the repository and switch to gh-pages branch
  git clone https://github.com/${{ github.repository }}.git github-pages
  cd github-pages

  # Create gh-pages branch if it doesn't exist or switch to it
  git checkout -b gh-pages || git checkout gh-pages

  # Pull the latest changes from the remote gh-pages branch with rebase
  git pull --rebase origin gh-pages

  # Copy the Allure report into the 'github-pages' directory
  cp -r ../allure-report/* .

  # Add, commit, and push the changes to the gh-pages branch
  git add .
  git commit -m "Deploy Allure report"
  git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ 
