name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - uses: actions/checkout@v4

    # Set up Node.js environment
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Install dependencies using npm
    - name: Install dependencies
      run: npm ci

    # Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Run Playwright tests with Allure reporter
    - name: Run Playwright tests
      run: npx playwright test --reporter=allure-playwright

    # Generate Allure report
    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    # Upload Allure report as artifact
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30

    # Optionally send email notifications (requires configuration)
    - name: Send Email Notification with Report Link
      uses: dawidd6/action-send-mail@v3
      with:
        smtp-server: smtp.gmail.com
        smtp-port: 587
        smtp-user: ${{ secrets.EMAIL_USER }}
        smtp-password: ${{ secrets.EMAIL_PASSWORD }}
        from: ${{ secrets.EMAIL_USER }}
        to: queckey@gmail.com
        subject: "Playwright Test Run Complete"
        body: |
          Playwright test run has completed. Please find the Allure report at the following link:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts
