name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Install Allure Commandline (via npm)
      run: |
        npm install -g allure-commandline --save-dev

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: allure-report/
        retention-days: 30

    - name: Send email with Allure report attachment using Mailgun API
      if: ${{ always() }}
      run: |
        # Install curl for API request
        sudo apt-get update
        sudo apt-get install -y curl

        # Prepare email with Mailgun API
        MAILGUN_API_KEY="${{ secrets.MAILGUN_API_KEY }}"
        MAILGUN_DOMAIN="${{ secrets.MAILGUN_DOMAIN }}"
        EMAIL_SUBJECT="GitHub Actions Test Completion Report"
        EMAIL_BODY="Your Playwright tests have completed successfully. Check the report in the attachment."
        EMAIL_TO="${{ secrets.NOTIFY_EMAIL }}"
        EMAIL_FROM="postmaster@${MAILGUN_DOMAIN}"

        # Log environment variables (sensitive data will be hidden automatically)
        echo "MAILGUN_API_KEY: $MAILGUN_API_KEY"
        echo "MAILGUN_DOMAIN: $MAILGUN_DOMAIN"
        echo "EMAIL_SUBJECT: $EMAIL_SUBJECT"
        echo "EMAIL_BODY: $EMAIL_BODY"
        echo "EMAIL_TO: $EMAIL_TO"
        echo "EMAIL_FROM: $EMAIL_FROM"

        # Debug: Check if the Allure report exists and log file details
        echo "Checking if Allure report directory exists..."
        ls -l allure-report/
        echo "Checking size of index.html file..."
        if [ -f allure-report/index.html ]; then
          echo "index.html exists, file size: $(stat -c %s allure-report/index.html) bytes"
        else
          echo "index.html not found, please check Allure report generation."
          exit 1
        fi

        # Debug: Show the curl command and send request
        echo "Sending email via Mailgun API..."
        curl -v -X POST "https://api.mailgun.net/v3/${MAILGUN_DOMAIN}/messages" \
          -u "api:$MAILGUN_API_KEY" \
          -F from="$EMAIL_FROM" \
          -F to="$EMAIL_TO" \
          -F subject="$EMAIL_SUBJECT" \
          -F text="$EMAIL_BODY" \
          -F attachment=@allure-report/index.html || echo "Failed to send email"
