name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # This allows manual trigger of the workflow

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Install Allure Commandline (via npm)
      run: |
        npm install -g allure-commandline --save-dev

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: allure-report/
        retention-days: 30

    - name: Install sendmail and send email with Allure report attachment
      if: ${{ always() }}
      run: |
        # Install sendmail
        sudo apt-get update
        sudo apt-get install -y sendmail

        # Prepare the email content
        email_subject="GitHub Actions Test Completion Report"
        email_body="Your Playwright tests have completed successfully.\n\nCheck the report in the attachment."

        # Prepare the email header
        email_header="Subject: ${email_subject}\nTo: ${{ secrets.NOTIFY_EMAIL }}\nContent-Type: multipart/mixed; boundary=\"boundary\"\n"

        # Prepare the email body and attachment
        boundary="boundary"
        report_file="allure-report/index.html"
        
        # Create the email content with base64 encoding for the attachment
        attachment=$(base64 < "${report_file}")
        email_content="--$boundary\nContent-Type: text/plain; charset=\"utf-8\"\nContent-Transfer-Encoding: 7bit\n\n$email_body\n\n--$boundary\nContent-Type: text/html; name=\"$(basename $report_file)\"\nContent-Transfer-Encoding: base64\nContent-Disposition: attachment; filename=\"$(basename $report_file)\"\n\n$attachment\n--$boundary--"

        # Send the email with the attached Allure report
        echo -e "$email_header$email_content" | sendmail -t

